apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: java-deployment
spec: 
  selector: 
    matchLabels: 
      app: java-app 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: java-app 
    spec: 
      containers: 
      - name: java-app 
        image:  agunuworld/hello-world-java
        ports: 
        - containerPort: 5000
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-app 
spec: 
  selector: 
    app: java-app 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5000
  type: LoadBalancer
